### ISSUE TITLE
Cannot get the tests to run (in Windows)

### ISSUE THREAD

**Issue by kr-eberle** [launchdarkly/js-client-sdk#116]
Hi,
I found a little bug in the typing.d.ts and wanted to fix it myself via pull request etc. 
I have tried to get myself set up (on a **Windows** machine), and found 
* that many of the NPM scripts don't work (probably because they are not cross-platform)
* that many of the tests fail.
I was able to locally fix some (not all) of the NPM scripts, but don't know what to do with the test failures. 

Find some of the test failures below.

If anybody knows how to get the process to work, that would be great :)

Thanks,
Krischan

```
d:\dev\imodeljs\js-client>npm run test

> ldclient-js@2.7.1 test d:\dev\imodeljs\js-client
> NODE_ENV=test jest

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ldclient-js@2.7.1 test: `NODE_ENV=test jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ldclient-js@2.7.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Krischan.Eberle\AppData\Roaming\npm-cache\_logs\2018-10-02T07_17_06_304Z-debug.log

d:\dev\imodeljs\js-client>npm run test

> ldclient-js@2.7.1 test d:\dev\imodeljs\js-client
> SET NODE_ENV=test & jest

 FAIL  src\__tests__\Stream-test.js
  ● Test suite failed to run

    D:\dev\imodeljs\js-client\src\__tests__\Stream-test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import EventSource, { sources } from './EventSource-mock';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/build/script_transformer.js:316:17)

 FAIL  src\__tests__\EventSender-test.js
  ● Test suite failed to run

    D:\dev\imodeljs\js-client\src\__tests__\EventSender-test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Base64 from 'Base64';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/build/script_transformer.js:316:17)
```

**Comment by kr-eberle** [comment]
FWIW, the actual bug which I intended to fix is this: LDOptions in typings.d.ts has the property **evaluationExplanations** whereas in index.js the respective property is called **evaluationReasons**:

> const requestor = Requestor(baseUrl, environment, options.useReport, **options.evaluationReasons,** sendLDHeaders);

I assume adjusting LDOptions in typings.d.ts is the less disruptive way to fix this.

**Comment by eli-darkly** [comment]
Thanks for catching the wrong property name. That's certainly easy to fix. We're looking into the other cross-platform issues - as you can probably guess, we've been pretty Linux-focused in our development of this project so I'm not surprised we've missed a few things like this.

**Comment by eli-darkly** [comment]
I'm having more trouble than I expected getting the tests to run in Windows at all. If you already have a branch with the changes you've made so far, could you link to it (or just a gist of what you've got in package.json)?

**Comment by eli-darkly** [comment]
Well, we would like to get the build working under Windows. But it sounds like you have had more luck so far than I've had. The environment variable issue is fairly easy to fix by changing it to use `cross-env` (as some of the other commands already do), but I can't get it to the point of actually running any tests; currently it is failing for me with "Module jest-localstorage-mock in the setupFiles option was not found."

So, if you have a version of package.json that works better than that, even if the tests don't pass yet, I would appreciate a chance to see it.

**Comment by kr-eberle** [comment]
Hi Eli,

my local changes to package.json are just to use cross-env in the test and test:junit scripts:

"test": "cross-env NODE_ENV=test jest",
"test:junit": "cross-env NODE_ENV=test jest --testResultsProcessor jest-junit",

My NPM version: 5.5.1
My Node version: v8.9.3

The steps I did:

  *   npm install -> changed package-lock.json (let me know if these are interesting to you)
  *   npm run build -> succeeded
  *   npm run test -> failed with:

FAIL  src\__tests__\EventProcessor-test.js
● Test suite failed to run

    D:\dev\imodeljs\js-client\src\__tests__\EventProcessor-test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import sinon from 'sinon';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (../node_modules/jest-runtime/build/script_transformer.js:316:17)

Thanks,
Krischan

**Comment by eli-darkly** [comment]
Thanks. Hmm. Well, that is what I did too. My npm version is 6.4.1, maybe that makes a difference.

**Comment by kr-eberle** [comment]
As you seem to be able to run the tests, would it make sense if you did that quick naming fix?

Krischan

**Comment by eli-darkly** [comment]
What I said in my last comment was that I'm _not_ able to run the tests.

However, we did do a release yesterday which fixes the TypeScript property name error.

**Comment by eli-darkly** [comment]
Hi. I know this is pretty late, but since your original report we've made many changes to the build, including some for Windows compatibility. We are now successfully running one of our CI builds of this repository in Windows. So if you're still interested and haven't already tried this again, I recommend trying it again.
