### ISSUE TITLE
Compatibility problem in 2.10.0 due to use of Promise.finally()

### ISSUE THREAD

**Issue by eli-darkly** [launchdarkly/js-client-sdk#151]
It's come to our attention that the 2.10.0 release is incompatible with some older browsers because it uses the `finally()` method of Promise, which was a more recent addition to the Promise standard.

We apologize for the mistake, and we will release a patch shortly that fixes this.

**Comment by eli-darkly** [comment]
We have released version 2.10.1, which fixes this issue. Note that while the new version should be available immediately via `npm`, there is a delay before the copy hosted at https://app.launchdarkly.com/snippet/ldclient.min.js will be on the new version; we will update this as soon as possible.

**Comment by PerStirpes** [comment]
#### [EdgeHTML Platform Status](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/promiseprototypefinally/?q=finally)
 `finally` is currently in development

**Comment by eli-darkly** [comment]
@PerStirpes Yes, I should've said "older browsers and also Edge." Unfortunately, some commonly used Promise polyfills don't support it either, so people who knew they would need to use a polyfill to support older browsers that didn't have native Promise support would still be out of luck.

**Comment by eli-darkly** [comment]
There was a delay in updating https://app.launchdarkly.com/snippet/ldclient.min.js but the fix is there too now.
