### ISSUE TITLE
Synchronous reading of bootstrap

### ISSUE THREAD

**Issue by edvinerikson** [launchdarkly/js-client-sdk#162]
**Describe the bug**
Calling `variation` before the ready event fire return `undefined` despite having bootstrap config provided.
**To reproduce**
Steps to reproduce the behavior.
https://jsbin.com/xuyatiniva/1/edit?html,output

**Expected behavior**
I expect that the reading of bootstrap is synchronous to allow for simpler integration in SSR react apps.

**SDK version**
2.12.2

**Additional context**
We will have to create a mock client for now and switch to the real client once the ready event is emitted.. but we're not really fond of that idea.

**Comment by bwoskow-ld** [comment]
Thanks for the feedback, @edvinerikson!

While LDClient's current behavior works as designed and documented, the behavior you described makes sense to us. We'll take a look at implementing this and will get back to you soon.

**Comment by eli-darkly** [comment]
This has been changed in the 2.12.3 release to behave in the way you expected (which was also the way it behaved in earlier versions of the SDK; unfortunately we hadn't documented the change).

**Comment by edvinerikson** [comment]
Thank you for such a fast response! 👍🏼
