### ISSUE TITLE
IE 11 compatibility issue due to startsWith

### ISSUE THREAD

**Issue by cvetanov** [launchdarkly/js-client-sdk#168]
**Describe the bug**
Application does not work in IE due to not supported method `startsWith`.

**To reproduce**
Any React application trying to use the `launchdarkly-react-client-sdk` package.

**Expected behavior**
Should work in IE since the [docs](https://docs.launchdarkly.com/docs/js-sdk-reference#section-browser-support) do not mention adding a polyfill for `String.prototype.startsWith` and seems like it was fixed in a [previous version](https://github.com/launchdarkly/js-client-sdk/blob/master/CHANGELOG.md#211---2018-06-05) of the client SDK

**Current workaround**
Adding a polyfill for `String.prototype.startsWith` ourselves.

**Logs**
`Object doesn't support property or method 'startsWith'`

**SDK version**
`"launchdarkly-react-client-sdk": "^2.12.4"`

**Language version, developer tools**
Not sure if relevant, but we are on React v16.8.6

**OS/platform**
Browser IE 11

**Additional context**
Most probably caused by the condition in [here](https://github.com/launchdarkly/js-client-sdk/blob/master/packages/launchdarkly-react-client-sdk/src/utils.ts#L8).

**Comment by cvetanov** [comment]
Most probably caused by this check [here](https://github.com/launchdarkly/js-client-sdk/blob/master/packages/launchdarkly-react-client-sdk/src/utils.ts#L8).

**Comment by eli-darkly** [comment]
Thanks for catching this! We'll have a patch out shortly.

**Comment by eli-darkly** [comment]
Fixed in the 2.12.5 release.
