### ISSUE TITLE
[React SDK] Expose a way to hook into LD Connection Errors

### ISSUE THREAD

**Issue by martinmckenna** [launchdarkly/js-client-sdk#175]
## The Problem

Currently, our app that relies on the LaunchDarkly service is render blocked by the actual LD Service. In other words, if the LD Service fails to connect, our app will never load.

Specifically if [this line fails](https://github.com/launchdarkly/js-client-sdk/blob/master/packages/launchdarkly-react-client-sdk/src/withLDProvider.tsx#L61), we never know.

This is in a nutshell how we use the React SDK

```js
import React from 'react'

export const App: React.FC<Props> = props => {
  const { userID } = props;

  /** PROBLEM: THIS MAY NEVER INIT AND BE UNDEFINED FOREVER */
  const client = useLDClient();

  const [isLoading, setLoading] = React.useState<boolean>(true)

  React.useEffect(() => {
    if (client && userID) {
      client
        .identify({
          key: userID
        })
        /**
         * set loaded to true if client fails or succeeds.
         * 
         * We don't want to render block if the flags can't be loaded.
         */
        .then(() => setLoading(false))
        .catch(() => setLoading(false));
    }
  }, [client, userID]);

  if (isLoading) {
    return null;
  }

  return <App />;
};

export default App;
```

but the issue here is that we have no way of knowing whether or not the connection succeeded.

## Ideal Solution

Provide a new prop, maybe called `ldConnectionError` to the `<WrappedComponent />` [here.](https://github.com/launchdarkly/js-client-sdk/blob/master/packages/launchdarkly-react-client-sdk/src/withLDProvider.tsx).

So that could open a consumer component up to the following possibilities

```js
import React from 'react'

export const App: React.FC<Props> = props => {
  const { userID } = props;

  const [client, clientError] = useLDClient();

  const [isLoading, setLoading] = React.useState<boolean>(true)

  React.useEffect(() => {
    if (client && userID) {
      client
        .identify({
          key: userID
        })
        /**
         * set loaded to true if client fails or succeeds.
         * 
         * We don't want to render block if the flags can't be loaded.
         */
        .then(() => setLoading(false))
        .catch(() => setLoading(false));
    }
  }, [client, userID, clientError]);

  if (isLoading && !clientError) {
    return null;
  }

  return <App />;
};

export default App;
```

**Comment by eli-darkly** [comment]
Ah - if you're not setting the environment ID at all, yes, that's a different problem that currently does not cause the client to become ready. The error is coming from the JS SDK code and I don't think there is currently a way for the React SDK code to get at it. I'll have to look into this a bit more to see the best way to address it.

**Comment by martinmckenna** [comment]
@eli-darkly Thanks. At the very least, I'd love to get an empty object for the flags, rather than bombing altogether.

**Comment by eli-darkly** [comment]
I've moved this issue over to the `react-client-sdk` repository: https://github.com/launchdarkly/react-client-sdk/issues/4
