### ISSUE TITLE
Streaming connection error causes endless console logs (Error on stream connection: {"isTrusted":true})

### ISSUE THREAD

**Issue by MattMcGlade123** [launchdarkly/js-client-sdk#182]
I'm using the streaming option In LD I'm getting continuous console error logs. This usually give a 503 error rather than any issue with 500. It does give an 'Access-Control-Allow-Origin' issue to. I expected the code to throw an error if there is an issue but not continuously. This is present on a new build using Hooks and an old build using the provider.

**To reproduce**
Set up LD using the latest Hooks option (https://docs.launchdarkly.com/docs/react-sdk-reference#section-hooks). Set the Streaming URL to a url. Run the App

**Expected behavior**
If there is an error I expect _one_ error log to show.

**Logs**
![Screenshot 2019-10-15 at 16 45 14](https://user-images.githubusercontent.com/56599928/66847383-328ab100-ef6b-11e9-86e1-d1a8d83a5a81.png)

**SDK version**
"launchdarkly-react-client-sdk": "^2.14.0",

**OS/platform**
Present on all browsers

**Comment by torchhound** [comment]
Hi @MattMcGlade123 thanks for the bug report but this is the incorrect repo. Please post this issue in the [react-client-sdk repo](https://github.com/launchdarkly/react-client-sdk).
