### ISSUE TITLE
Copyright line is incomplete

### ISSUE THREAD

**Issue by jazpearson** [launchdarkly/js-client-sdk#202]
Not really a bug, but shouldn't the copyright line be updated accordingly?

https://github.com/launchdarkly/js-client-sdk/blob/bb4116cf76e1b1f2278e38d53eb1df4eb8fa0fd2/LICENSE#L189

e.g.
```
Copyright 2016 Catamorphic, Co.
```

**Comment by eli-darkly** [comment]
Hmm, actually, this isn't even the right file. It is supposed to be the Apache short form like [this](https://github.com/launchdarkly/go-server-sdk-private/blob/v4/LICENSE.txt); instead it looks like we accidentally copied in the _instructions_ for attaching a license. The correct file was present in [earlier versions](https://github.com/launchdarkly/js-client-sdk/blob/2.0.0/LICENSE.txt) and it's easy to restore— thanks for pointing that out.
