### ISSUE TITLE
Reloading page causes stream error

### ISSUE THREAD

**Issue by erlendp** [launchdarkly/js-client-sdk#249]
### Describe the bug
I posted this on the React library github issue page (https://github.com/launchdarkly/react-client-sdk/issues/123#issue-1170305480), but looks like it may be more related to the core JS library, so reposting it here instead.

When reloading the React app, the following error is reported on the console:

`Error on stream connection: {"isTrusted":true}, will continue retrying every 1000 milliseconds.`

This is causing many errors to flood our logs (the error only appears once per reload of the browser page).

### To reproduce

- `yarn create react-app launchdarkly-test`
- `cd launchdarkly-test`
- `yarn add launchdarkly-react-client-sdk`
- Wrap the App component in the withLDProvider HOC:

```
export default withLDProvider({
  clientSideID: 'xxxxxxx',
})(App);
```
- `yarn start`
- Ensure 'preserve logs' is checked.
- Reload page, and the error is reported on the console.

### Expected behavior
No error to be reported on reload.

### Logs
[LaunchDarkly] Error on stream connection: {"isTrusted":true}, will continue retrying every 1000 milliseconds.

### Version
React SDK version: 2.25.1
Browser: Chrome 99.0.4844.83 (Official Build) (x86_64)
OS: Mac OSX 12.0.1

**Comment by louis-launchdarkly** [comment]
Hello @erlendp, thank you for reaching out, we will look at this and give you an update once we investigate the issue.

_Filed Internally as 147957_

**Comment by gautamkr04** [comment]
Hi , 
I have similar issue when we have long lived connection (24hr) observed that flag set to false  , and re render for when flag is true. To Work again need to reload the page again.

it is very intuitive to user to observe that next day there are some issue.

```
const useInitialiseLDContext = () => {
    const { data: userProfile } = useAssumeGetUserProfileInfoQuery();
    let ldClient = useLDClient();
    const storedEmail = localStorage.getItem('email');

    // Initialise when client is available
    useEffect(() => {
        if (ldClient && storedEmail) {
            ldClient.identify(getLDContextObject({ email: storedEmail }));
        }
    }, [ldClient]);

    // change context when email doesn't exists , and company_group_id added.
    useEffect(() => {
        const handleVisibilityChange = () => {
            console.log(document.visibilityState, 'hook visible state');
            if (ldClient) {
                console.log('hook visible state \n', document.visibilityState, '\n hook ldClient', ldClient, '\n context    ', ldClient?.getContext());
            }
            if (document.visibilityState === 'visible' && ldClient) {
                const { email, company_group_id } = userProfile?.data || {};

                // Set email in localStorage if not already set and update to launchdarkly
                if (!storedEmail && email) {
                    localStorage.setItem('email', email);
                    ldClient.identify(getLDContextObject({ email }));
                }

                // Identify the user with the specific company_group_id if available
                if (company_group_id) {
                    const oldContext = ldClient.getContext();
                    ldClient.identify({ ...oldContext, company_group_id });
                }
            }
        };

        document.addEventListener('visibilitychange', handleVisibilityChange);

        return () => {
            document.removeEventListener('visibilitychange', handleVisibilityChange);
        };
    }, [ldClient, userProfile?.data]);
};

**we call it inside App.tsx**
<LDProvider clientSideID={environment.launchDarkly_client_SDK_key}>
     <AppRoutes />
</LDProvider>

**and inside AppRoutes call useInitialiseLDContext **
useInitialiseLDContext();
```

Can some one please help .
