### ISSUE TITLE
Bypass "do not track" setting in development environment

### ISSUE THREAD

**Issue by leonard-henriquez** [launchdarkly/js-client-sdk#288]
**Describe the bug**
A few members of my dev team are using the Arc browser which has "Do Not Track" setting enabled by default.
According to LD documentation, events are not collected when "Do Not Track" is detected.
Seems fine in general, but there is no way to disable it in development environment.
For the third time in a few weeks, I lost a few hours of developers who struggled to understand why their events weren't log in the "Live Events" page.

**To reproduce**
Use Arc or enable the  "Do Not Track" setting on your browser.
Go on a website where you use Launch Darkly.
Check that you **don't** receive events in the "Live Events" page on Launch Darkly

**Expected behavior**
I would to have a setting to bypass the "Do Not Track" setting in specific environments.

**SDK version**
Latest version of the React SDK

**Comment by louis-launchdarkly** [comment]
Hello @leonard-henriquez, thank you for the request. We have discussed this internally and decided we cannot implement this feature request. LaunchDarkly SDKs do not have the concept of "Is this environment a development environment?", so there is no way to limit such a setting to development. This can be misused and hurt both LaunchDarkly customers' and LaunchDarkly's trust with the end users.

One suggestion we have is to create an onboarding guide for your developers to remind them to disable the Arc browser's DoNotTrack setting before starting development.
